services:
  - type: web
    name: fampay-gateway
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FAMPAY_API_KEY
        value: FAM_9D6E3230864644382B11215E46E93283144AE8A4
      - key: FAMPAY_API_URL
        value: https://fampaygateway.site/api/create_order.php
      - key: SECRET_KEY
        generateValue: true